spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  sql:
    # 后期在处理
    init:
      mode: never
      # 启动执行建表脚本
      schema-locations: classpath:sql/init/schema.sql
      # 启动执行初始数据脚本
      data-locations: classpath:sql/init/data.sql
  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms